# config/_default/languages.en.toml

title = "HAQ"

[author]
name = "Hub for Astronomy in Queensland"
image = "/img/logo_small.png"
headline = ""
bio = ""

links = [
  { twitter = "https://twitter.com/re_mcelroy" },
  { github = "https://github.com/Astro-Queensland" },
  { email = "mailto:rebecca.mcelroy@unisq.edu.au" },
  ]