# config/_default/languages.en.toml

title = ""

[author]
name = "Dr Rebecca McElroy"
image = ""
headline = ""
bio = ""

links = [
  { twitter = "" },
  { github = "" },
  { linkedin = "" },
  { email = "mailto:rebecca.mcelroy@unisq.edu.au" },
  { instagram = ""},
  { orcid = ""}
  ]