# config/_default/languages.en.toml

title = "HAQ"

[author]
name = "Hub for Astronomy in Queensland"
image = "/img/logo_small.png"
headline = "Facilitating collaborations between Queensland's Astronomy "
bio = ""

links = [
  { twitter = "https://twitter.com/re_mcelroy" },
  { github = "https://github.com/rebeccamcelroy" },
  { linkedin = "https://www.linkedin.com/in/rebecca-mcelroy/" },
  { email = "mailto:rebecca.mcelroy@unisq.edu.au" },
  { instagram = "https://www.instagram.com/paintingbybex/"},
  { orcid = "https://orcid.org/0000-0002-7960-5808"}
  ]