# config/_default/menus.toml

[[main]]
  name = "People"
  weight = 1

[[main]]
  name = "UniSQ"
  parent = "People"
  pageRef = "people_usq"
  weight = 1

[[main]]
  name = "UQ"
  parent = "People"
  pageRef = "people_uq"
  weight = 2

[[main]]
  name = "QUT"
  parent = "People"
  pageRef = "people_qut"
  weight = 3

[[main]]
  name = "Admin"
  parent = "People"
  pageRef = "admin"
  weight = 3

[[main]]
  name = "Mailer"
  pageRef = "mailer"
  weight = 2

[[main]]
  name = "Events"
  pageRef = "events"
  weight = 3

