# config/_default/menus.toml

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Hubs"
  weight = 20

[[main]]
  name = "USQ"
  parent = "Hubs"
  pageRef = "hubs_usq"
  weight = 1

[[main]]
  name = "UQ"
  parent = "Hubs"
  pageRef = "hubs_uq"
  weight = 2

