# config/_default/menus.toml

[[main]]
  name = "About Me"
  weight = 20

[[main]]
  name = "Bio"
  parent = "About Me"
  pageRef = "about_me"
  weight = 20

[[main]]
  name = "CV"
  parent = "About Me"
  url = "cv_rmcelroy.pdf"
  weight = 20

[[main]]
  name = "Resume"
  parent = "About Me"
  url = "resume_rmcelroy.pdf"
  weight = 20


[[main]]
  name = "Art"
  weight = 20

[[main]]
  name = "What I do"
  parent = "Art"
  pageRef = "art_about"
  weight = 20

[[main]]
  name = "Insta"
  parent = "Art"
  url = "https://www.instagram.com/paintingbybex"
  weight = 20

[[main]]
  name = "Science art"
  parent = "Art"
  weight = 20


